---
title: "Research"
---
Last Updated: June 2023

[Google Scholar Page](https://scholar.google.com/citations?hl=en&user=9ZauRjcAAAAJ)

[SSRN Author Page](https://papers.ssrn.com/sol3/cf_dev/AbsByAuth.cfm?per_id=891507)

[Research Gate Page](https://www.researchgate.net/profile/Justin_Ross)

**Research Interests**: State and local public finance; property taxation; fiscal zoning; public choice

>*Taxes formalize our obligations to each other. They define the inequalities we accept and those that we collectively seek to redress. They signify who is a member of our political community, how wide we draw the circle of “we.” They set the boundaries of what our governments can do. In the modern world, taxation is the social contract.*
>~Isaac William Martin, Ajay K.Mehrotra, and Monica Prasad in "The New Fiscal Sociology" (2009)

I view the public finance system a laboratory for testing social theory. That is, choices made over how to tax and spend reflect (at least partially) societal values and constraints. I particularly prefer to put the government itself at the center of the analysis in my work.

My research is featured in outlets like the National Tax Journal, Journal of Public Economics, Land Economics, Journal of Environmental Economics & Management, Public Finance Review, Southern Economic Journal, Public Budgeting & Finance, Journal of Public Administration Research & Theory, Public Administration Review, State Tax Notes, Contemporary Economic Policy, Journal of Housing Economics, Public Finance & Management and the Journal of Real Estate and Finance Economics.  

#### PUBLISHED PEER REVIEW

"**[Review of 'The Three Pillars Approach to Broadening the Federal Funding Base for Federal Election Grants.'](https://electioncenter.org/wp-content/uploads/2026/01/JEARP-Volume-04-Special.pdf#page=119.06)"** Ross, Justin and Keely Varvel. (2025). *Journal of Election Administration, Research, and Practice* 4(3): 113-4.

"[**Is Trust in Local Government Influenced by the ``Marketplace" of Choice?**](https://onlinelibrary.wiley.com/doi/10.1111/puar.13869)." Peng, Lanjun and Justin M. Ross. (2025). *Public Administration Review* 85(3): 768-86.

“[**Does the Federal Budget Process Matter for Fiscal Sustainability?**](https://journals.sagepub.com/doi/abs/10.1177/10911421241273374)” Duncan, Denvil, Justin M. Ross, and John L. Mikesell. (2024). *Public Finance Review* 53(1): 29-61.

“[**By the people, for the people: Local governments' representation of voter preferences under the Affordable Care Act.**](https://doi.org/10.1111/pbaf.12359)” Perez, Victoria, Justin M. Ross, and Kosali Simon. (2024). *Public Budgeting \& Finance* 44(2): 90-161.

"[**Use Tax Administration and Revenue Production in the States**](https://doi.org/10.1111/pbaf.12350)" John L. Mikesell, John D. Stavick, and Justin M. Ross. (2023). *Public Budgeting \& Finance* 43(4): 24-43.

"[**Too Small to Fail: The Role of Medicaid in Mitigating Pandemic-Related Fiscal Strain on Local Governments**](doi/10.1111/pbaf.12298)." (2021). Victoria Perez, Justin Ross, and Joseph A. Benitez. *Public Budgeting \& Finance* 41(3): 74-97.

"[**After Wayfair: What are State Use Taxes Worth?**](http://dx.doi.org/10.2139/ssrn.3397342)" (2019). Mikesell, John L. and Justin M. Ross. *National Tax Journal*, December 72(4): 801-20.

"[**The Impact of State Taxes on Pass-Through Businesses: Evidence from the 2012 Kansas Income Tax Reform.**](https://doi.org/10.1016/j.jpubeco.2019.03.008)" (2019). Debacker, Jason, Bradley T. Heim, Shanthi P. Ramnath, and Justin M. Ross. *Journal of Public Economics*, June 174: 53-75.

"[**Pass-Through Entity Responses to Preferential Tax Rates: Evidence on Owner compensation and Economic Activity in Kansas.**](http://doi.org/10.17310/ntj.2018.4.05)" (2018). Debacker, Jason M., Lucas Goodman, Bradley T. Heim, Shanthi P. Ramnath, & Justin Ross. *National Tax Journal* 71(4): 687-706.

"[**Fiscal Zoning and Fiscal Externalities.**](http://dx.doi.org/10.2139/ssrn.2816566)" (2018). Ross, Justin M. *National Tax Journal* 70(1): 45-74.

"[**Unfunded Mandates and Fiscal Structure: Empirical Evidence from a Synthetic Control Model.**](https://doi.org/10.1111/puar.12867)" (2018). Ross, Justin M. *Public Administration Review* 78(1): 92-103.

"[**The Effect of Fiscal Illusion on Public Revenue: Evidence from Local Government Property Assessment.**](https://doi.org/10.1177/1091142116676360)" (2018). Ross, Justin M. and Sian Mughan. *Public Finance Review* 46(4): 635-64.

"[**The Labor Incidence of Capital Taxation: New Empirical Evidence from the Retail Sales Taxation of Manufacturing Machinery and Equipment.**](http://dx.doi.org/10.2139/ssrn.2462288)" (2017). Mikesell, John M. and Justin Ross. *National Tax Journal* 70(2): 257-94.

"[**Indiana's Property Tax Caps: Old Idea, New Approach, and Surprising Incentives.**](https://doi.org/10.1111/pbaf.12073)" (2015). Ross, Justin M., Madeline Ferrell, and Kate Yang. *Public Budgeting & Finance* 35(4): 18-41.

"[**The Public Financing of America's Largest Cities: A Study of City Financial Records in the Wake of the Great Recession.**](https://doi.org/10.1111/jors.12117)" (2015). Ross, Justin M., Wenli Yan, and Craig Johnson. *Journal of Regional Science* 55(1): 113-38.

"[**Could Land-Only Taxation Save Local Governments in Indiana?**](https://doi.org/10.20899/jpna.1.1.29-42)" (2015). Ross, Justin M. and Gyeoreh Lee. *Journal of Public and Nonprofit Affairs* 1(1): 29-42.

"[**State Revenue Forecasts and Political Acceptance: The Value of Consensus Forecasting in the Budget Process.**](https://doi.org/10.1111/puar.12166)" (2014). Mikesell, John L. and Justin M. Ross. *Public Administration Review* 74(2): 188-203.

"[**Fiscal Illusion from Property Reassessment? An Empirical Test of the Residual View.**](http://dx.doi.org/10.2139/ssrn.1969015)" (2013). Justin M. Ross and Wenli Yan. *National Tax Journal* 66(1): 7-32.

"[**A Socioeconomic Analysis of Property Assessment Uniformity: Empirical Evidence on the Role of Policy.**](https://doi.org/10.1111/j.1540-5850.2013.12001.x)" (2013). Justin M. Ross. *Public Budgeting & Finance* 33(1): 49-75.

"[**Frictions in Polycentric Administration with Non-Congruent Borders: Evidence from Ohio School District Class Sizes**](https://doi.org/10.1093/jopart/mus090)" (2014). Justin M. Ross, Joshua C. Hall, and William Resh. *Journal of Public Administration Research & Theory* 24(3): 623-49. doi: 10.1093/jopart/mus90 

"[**Are Community-Nuisance Fiscal Zoning Arrangements Undermined by State Property Tax Reforms? Evidence from Nuclear Power Plants and School Finance Equalization.**](http://dx.doi.org/10.2139/ssrn.2038478)" (2013). Justin M. Ross. *Land Economics* 89(3): 449-65.

"[**School District Income Taxes: New Revenue or a Property Tax Substitute?**](https://doi.org/10.1111/j.1540-5850.2013.12004.x)" (2013). Justin M. Ross and Phuong H. Nguyen. *Public Budgeting & Finance* 33(2): 19-40.

"[**Strategic Tax Planning for State Tax Amnesties: Evidence from Eligibility Period Restrictions.**](https://doi.org/10.1177/1091142112461687)" (2013). Justin M. Ross and Neal W. Buckwalter. *Public Finance Review* 41(3): 275-301.

"[**Fast Money? The Contribution of State Tax Amnesties to Public Revenue Systems.**](http://dx.doi.org/10.17310/ntj.2012.3.02)" John L. Mikesell and Justin M. Ross. (2012). *National Tax Journal* 65(3): 529-62.

"[**Interjurisdictional Determinants of Property Assessment Regressivity.**](http://dx.doi.org/10.2139/ssrn.1724690)" Justin M. Ross. *Land Economics* (February 2012), Vol. 88, Issue 1: 28-42.

"[**Local Government Property Tax Amnesty Programs: Structures and Themes.**](http://dx.doi.org/10.2139/ssrn.2007509)" Justin M. Ross. (2012.) *Public Finance and Management* 12(2): 146-173.

"[**Revealed Preference for Relative Status: Evidence from the Housing Market.**](https://doi.org/10.1016/j.jhe.2012.01.001)" Susane J. Leguizamon and Justin Ross. (2012). *Journal of Housing Economics* 21: 55-65.

"[**Robustness and Vulnerability of Community Irrigation Systems: The Case of the Taos Valley Acequias.**](https://doi.org/10.1016/j.jeem.2010.10.004)" Michael E. Cox and Justin M. Ross. (2011). *Journal of Environmental Economics and Management* 61(3): 254-66.

"[**Assessor Incentives and Property Assessment.**](https://doi.org/10.4284/sej.2011.77.3.776)" Ross, J.M. (2011). *Southern Economic Journal* 77(3): 776-94.

"[**Inconsistency in Welfare Inferences from Distance Variables in Hedonic Regressions.**](https://doi.org/10.1007/s11146-009-9221-z)" Ross, J.M., Michael Farmer, and Cliff Lipscomb. (2011). *Journal of Real Estate and Finance Economics* 43 (3): 385-400.  FAQ's.

"[**Tiebout Competition, Yardstick Competition, and Tax Instrument Choice: Evidence from Ohio School Districts.**](https://doi.org/10.1177/1091142110373479)" Joshua C. Hall and Justin M. Ross. (2010). *Public Finance Review* 38(6): 710-37.

"[**Does State Spending on Mental Health Lower Suicide Rates?**](https://doi.org/10.1016/j.socec.2010.10.005)" Justin M. Ross, Pavel Yakovlev, and Fatima Carson. (2012). *Journal of Socio-Economics* 41(4): 408-417.

"[**Do Surveys of Experts Provide Unbiased Judgments? Evidence from College Football Rankings**](https://doi.org/10.1111/j.1465-7287.2011.00275.x)" Justin M. Ross, Sarah Larson, and Chad Wall. (2012). *Contemporary Economic Policy* 50(4): 502-522.

"[**New Empirical Estimates of Rent-Seeking: An Update of Sobel and Garrett  [2002].**](https://doi.org/10.1332/251569209X15665367046615)" (2009).  Joshua C. Hall and Justin M. Ross.  *Journal of Public Finance and Public Choice* 27(2-3): 125-136.

"[**What Should Policy Makers Know When Economists Say "Market" Failure?**](https://ssrn.com/abstract=1724638)" Ross, J.M. (2009). *Georgetown Public Policy Review*, 14(1), pp. 27-32.

 "[**A Theoretical Model of the Distribution of Teacher Attention Under Benchmark Testing.**](https://ssrn.com/abstract=1259749)" Ross, J.M. (2008). *Economics Bulletin* 9(29), pp. 1-8.

“[**Income Tax Responsiveness of the Rich: Evidence from Free Agent MLB All-Stars.**](https://doi.org/10.1111/j.1465-7287.2007.00078.x)” Ross, J.M. and Robert Dunn. (2007). *Contemporary Economic Policy* 25(4), pp. 639-48.  Ungated Version.  DATA



#### Working Papers

"[**The Effect of AirBNB on Housing Prices: Evidence from the 2017 Solar Eclipse**](https://papers.ssrn.com/sol3/papers.cfm?abstract_id=5262252)" (w/Denvil Duncan). Under Review.

"[**State Versus Local Tax Enforcement Effectiveness: Evidence from Airbnb.**](https://papers.ssrn.com/abstract=6030515)" (w/Luis Navarro and Whitney Afonso). Under Review.

"**Is There Still A Role For Classical Public Finance? Challenges from AI and Identity Politics.**" Revise and Resubmit at *Perspectives on Public Management and Governance*.

"[**Do Tax Incentives for Farmland Supply Induce New Farm Start-Ups? Evidence from Iowa's Beginning Farmer Tax Credit**](https://papers.ssrn.com/sol3/papers.cfm?abstract_id=5146352)" (w/Wesley Zebrowski and Julia C.D. Valliant). Revise and Resubmit at *Applied Economic Perspectives and Policy.*

"[**Do Local Governments Site Nuisance Activities Along Borders? A Empirical Strategy Applied to Wind Turbines**](https://papers.ssrn.com/sol3/papers.cfm?abstract_id=2882208)." (with Sanya Carley)

"[**Consumer Incidence in Sales Tax Holidays: Evidence from Tennessee.**](https://papers.ssrn.com/sol3/papers.cfm?abstract_id=2986456)" (with Felipe Lozano-Rojas). 

"[**Are Back-To School Sales Tax Holidays Progressive or Regressive?**](https://papers.ssrn.com/sol3/papers.cfm?abstract_id=3392108)" (with Felipe Lozano-Rojas)




#### Works in Progress


"The Effect of State Occupational Licensing of Paid Tax Preapration on Tax Professional Services." (with/Coady Wing and Denvil Duncan)

"Fixed Costs as a Source of Market Power in the Gig Economy: Evidence from Airbnb." (with Denvil Duncan)

"Real Property Taxation: The Definition of Property Values as a Problem of Fiscal Policy" (with John Mikesell)

"Did State Imposed Tax & Expenditure Limits Reduce the Fiscal Size of Local Governments? Revisiting the Evidence"(with John Stavick and Patrick Carlin).


#### BOOK AND SYMPOSIUM CONTRIBUTIONS

"Welfare Effects of Selective Taxation: Economic Efficiency as a Normative Principle." (2018). Ross, Justin M. In For Your Own Good Good: Taxes, Paternalism, and Fiscal Discrimination in the Twenty-First Century, edited by Adam J. Hoffer and Todd Nesbit, The Mercatus Center.

Carbon Tax Guide : A Handbook for Policy Makers. (2017). World Bank, Washington, DC.  

"State Tax Amnesty: How a Standard Feature of American State Tax Administration Has Changed Over Thirty Years." Mikesell, John L. and Justin M. Ross. (2013).  State Tax Notes 67(7): 481-95.

"Local Government Lessons from Amnesty Programs for Property Tax Delinquents." Justin M. Ross. Forthcoming in Government Finance Review.

"Amnesty for Property Tax Delinquents?" Justin M. Ross. State Tax Notes 68(12): 919-28.

"Controversies in Property Assessment." Justin M. Ross and Denvil R. Duncan. (2012). Papers and Proceedings of the 105th Annual Conference on Taxation: 120-23. 

"Property Taxes and Polycentricity." Ross, Justin M. and Daniel Hummel. (2012). In The Annual Proceedings of the Wealth and Well-Being of Nations Volume IV 2011-2012, edited by Emily Chamlee-Wright.

"`Will You Stop That Infernal Racket!?!' Externalities and The Simpsons." In Homer Economicus: The Simpsons and Economics. Edited by Joshua C. Hall, forthcoming (Stanford University Press).

"When It Comes to Taxes: Focus on Being Competitive." Ross, J.M. and J.C. Hall. Chapter 5 in Unleashing Capitalism: Why Prosperity Stops at the West Virginia Border and How to Fix It, edited by Russell Sobel, 2007.

"Getting It Right: Where University Systems Lose Information in Designing Programs." Ross, J.M. In Doing More With Less: Making Colleges Work Better. Edited by Joshua C. Hall. Springer (2010).

"Managing the Internal Organization of Colleges and Universities." M. Holian and J.M. Ross. In Doing More With Less: Making Colleges Work Better. Edited by Joshua C. Hall. Springer (2010).

"U.S. Department of Housing and Urban Development." J.C. Hall and J.M. Ross in Booms and Busts: An Economics Encyclopedia, Mehmet Odekon (ed), M.E. Sharpe, forthcoming.

"When It Comes to Taxes in South Carolina: Focus on Being Competitive."  Ross, J.M., Joshua C. Hall, Peter T. Calcagno.  Chapter 4 in Unleashing Capitalism: A Prescription for Economic Prosperity in South Carolina, edited by Peter T. Cacagno, (2009).



#### POLICY STATEMENTS, OP-EDS, AND WHITE PAPERS

"Federalism and Polycentric Government in a Pandemic." Victoria Perez and Justin M. Ross. (2020). Mercatus Center at George Mason University, COVID-19 Policy Brief.

"Housing Supply Expansion and Local Government Finance." Justin Ross. (2020). Center for Rural Engagement, Housing Ready Toolkit. (Model and User Guide)

"Don't Rely on Balanced Budget Amendments to Keep Indiana Solvent." Justin Ross. (2019). Indiana Business Journal.  March 27, 2019.

"A Fiscal History of Indiana Local Government." Craig Johnson and Justin Ross. (2018). Indiana Fiscal Policy Institute.

"Are Sugar-Sweetened Beverage Taxes Regressive? Evidence from Household Retail Purchases." Justin M. Ross and Felipe Lozano-Rojas. (2018). Tax Foundation Fiscal Fact No. 592.

"Gross Receipts Taxes: Theory and Recent Evidence." Justin M. Ross. (2016). Tax Foundation Fiscal Fact No. 529.

"A Tax Increase Hidden in Your House." Justin Ross and Eileen Norcross. Washington Post. September 18, 2015.

"Indiana's Property Tax Caps: Effects on Equity, Service Delivery, and Tax Competitiveness." By Justin M. Ross and Caitlin Cheek. (2015). Issue Brief for the Fiscal Benchmarking Project.

"A Primer on State and Local Tax Policy: Trade-Offs Among Tax Instruments." (2014). Published by the Mercatus Center.

"Fiscal Analysis for Lake County, Indiana." Justin M. Ross and Madeline Dinges. 

"Property Tax Amnesty." by Justin M. Ross (June 26, 2012). Policy opinion memo prepared for the state legislature of Ohio.

"The Elective Zoning Proposal." By Justin M. Ross (February 2, 2012). Policy opinion memo prepared for Bonner County (Idaho) government.

"The Business Case for Product Philanthropy." Justin Ross and Kellie McGiverin-Bohan. Published by Good360.

#### BOOK REVIEWS

"Book Review: Youngman, Joan. (2016). A Good Tax: Legal and Policy Issues for the Property Tax in the United States." Ross, J.M. (2017). National Tax Journal 70(1).

"Book Review: Audretsch, David B., Flack, Oliver, & Heblich, Stephan (Eds.) (2009). Innovation and Entrepreneurship." Ross, J.M. (2009). The Review of Regional Studies. 39(2): 227-237.

* This paper won the 2007 West Virginia University Department of Economics Publishing Award.

**This paper has the won the 2007 West Virginia University Vickers Doctoral Student Research Paper Award. 

***This paper was nominated for "research article of the year award" by the IAOO in 2013.